baseURL = "http://whynot.guide/"
languageCode = "en-us"
title = "WhyNot.Guide"
theme = ["minimal"]
#enableGitInfo = true
enableRobotsTXT = true


[params]
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "rust", "python"]
    Description = ""
    profilePic = ""


[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:anderen2@whynot.guide"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/anderen2/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/andreas-skoglund/"
    name = "fab fa-linkedin"
    weight = 4
